# Generated by Django 6.0.3 on 2026-03-31 12:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='housingpreference',
            name='name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transportinfo',
            name='name',
        ),
        migrations.AlterField(
            model_name='transportinfo',
            name='arrival_method',
            field=models.CharField(choices=[('own_car', 'Oma autoga / Own car'), ('bus', 'Bussiga / Bus'), ('taxi', 'Takso/Bolt'), ('with_someone', 'Sõidan kaasa / Getting a ride'), ('other', 'Muu / Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.photogallery'),
            preserve_default=False,
        ),
    ]
