# Generated by Django 6.0.3 on 2026-03-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_photo_options_remove_housingpreference_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(upload_to='photos/'),
        ),
    ]
