# Generated by Django 6.0.3 on 2026-04-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rsvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='user',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
