# Generated by Django 6.0.3 on 2026-04-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_rsvp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='session_key',
            field=models.CharField(default=123, max_length=40),
            preserve_default=False,
        ),
    ]
