# Generated by Django 6.0.3 on 2026-04-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rsvp_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
    ]
